const products = [
  {
    id: 0,
    name: "PER white",
    price: 29.99,
    instock: 100,
    description: "V-Neck,Baumwollmix",
    imgSrc: "./img/t1.png",
  },
  {
    id: 1,
    name: "PER black",
    price: 24.99,
    instock: 43,
    description: "V-Neck,Baumwollmix",
    imgSrc: "./img/t2.png",
  },
  {
    id: 2,
    name: "JARL melange",
    price: 19.99,
    instock: 10,
    description: "V-Neck,Baumwollmix",
    imgSrc: "./img/t3.png",
  },
  {
    id: 3,
    name: "FINN",
    price: 25.99,
    instock: 5,
    description: "100% Baumwolle",
    imgSrc: "./img/t4.png",
  },
  {
    id: 4,
    name: "FINN rose",
    price: 29.99,
    instock: 4,
    description: "100% Baumwolle",
    imgSrc: "./img/t5.png",
  },
  {
    id: 5,
    name: "FINN midnight",
    price: 39.99,
    instock: 40,
    description: "100% Baumwolle",
    imgSrc: "./img/t6.png",
  },
];
